### ISSUE TITLE
when the plugin manager is started in a terminal (ssh) offer to create a BUI config 

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/PluginManager#1]
Currently you need a GUI environment for the plugin manager. Add some option to it to create a BUI config (when started in GUI, maybe under some "options" dialog). 

If the plugin manager is not started with a graphical user interface, add an INPUT to ask "The Plugin Manager needs a graphical user interface. Do you want to publish it as BUI to run it in the browser?" and if confirmed execute the BUI publish and display the URL for running it.

**Comment by SebastianAdams** [comment]
This has been implemented.
